/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpigpio_Pigpio */

#ifndef _Included_jpigpio_Pigpio
#define _Included_jpigpio_Pigpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioInitialize
  (JNIEnv *, jobject);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioTerminate
  (JNIEnv *, jobject);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioSetMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioSetMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioGetMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpigpio_Pigpio_gpioGetMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioSetPullUpDown
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioSetPullUpDown
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioRead
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jpigpio_Pigpio_gpioRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioWrite
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioWrite
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     jpigpio_Pigpio
 * Method:    i2cOpen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jpigpio_Pigpio_i2cOpen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    i2cClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_i2cClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    i2cReadDevice
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_jpigpio_Pigpio_i2cReadDevice
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     jpigpio_Pigpio
 * Method:    i2cWriteDevice
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_i2cWriteDevice
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioDelay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioDelay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioTick
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jpigpio_Pigpio_gpioTick
  (JNIEnv *, jobject);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioServo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioServo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioSetAlertFunc
 * Signature: (ILjpigpio/Alert;)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioSetAlertFunc
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioTrigger
 * Signature: (IJZ)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_gpioTrigger
  (JNIEnv *, jobject, jint, jlong, jboolean);

/*
 * Class:     jpigpio_Pigpio
 * Method:    spiOpen
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jpigpio_Pigpio_spiOpen
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    spiClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_spiClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     jpigpio_Pigpio
 * Method:    spiRead
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_jpigpio_Pigpio_spiRead
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     jpigpio_Pigpio
 * Method:    spiWrite
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_jpigpio_Pigpio_spiWrite
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     jpigpio_Pigpio
 * Method:    spiXfer
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_jpigpio_Pigpio_spiXfer
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     jpigpio_Pigpio
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jpigpio_Pigpio_setDebug
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jpigpio_Pigpio
 * Method:    gpioxPulseAndWait
 * Signature: (IIJJZ)J
 */
JNIEXPORT jlong JNICALL Java_jpigpio_Pigpio_gpioxPulseAndWait
  (JNIEnv *, jobject, jint, jint, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
